# Generated by Django 4.2.5 on 2024-01-13 10:14

from django.db import migrations, models
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyApiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='contact phone number', max_length=31)),
                ('dob', models.DateField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
