# Generated by Django 4.2.5 on 2024-01-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myapimodel',
            name='phone',
        ),
    ]
